#!/usr/bin/env bash

export PATH=/opt/homebrew/bin:$PATH

sudo -v

# Keep-alive: update existing `sudo` time stamp until installation has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install rosetta
if [[ `uname -m` == 'arm64' ]]; then
    softwareupdate --install-rosetta --agree-to-license
fi

# Install brew
if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

# Update Homebrew recipes
brew update

# Install all our dependencies with bundle (See Brewfile)
brew tap homebrew/bundle
brew bundle

touch $HOME/.hushlogin

# Install crontab entries
crontab ./crontab

# Create a Code directory
mkdir $HOME/Code
cd $HOME/Code
$HOME/.composer/vendor/bin/valet park
cd -

# Symlink the Mackup config file to the home directory
ln -s $HOME/.dotfiles/mackup.cfg $HOME/.mackup.cfg

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/zsh/zshrc $HOME/.zshrc

# Setup global gitignore
git config --global core.excludesfile ~/.gitignore

# Install Depy
chown "$USER" /opt
git clone https://github.com/ivandokov/depy.git /opt/depy
cd /opt/depy
./install
