#!/usr/bin/env bash

export PATH=/opt/homebrew/bin:$PATH

sudo -v

# Keep-alive: update existing `sudo` time stamp until installation has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Install rosetta
if [[ `uname -m` == 'arm64' ]]; then
    softwareupdate --install-rosetta --agree-to-license
fi

# Install brew
if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

# Update Homebrew recipes
brew update

# Install all our dependencies with bundle (See Brewfile)
brew tap homebrew/bundle
brew bundle

touch $HOME/.hushlogin

# Install crontab entries
crontab $HOME/.dotfiles/crontab

# Create a Code directory
mkdir -p $HOME/Code

# Symlink the Mackup config file to the home directory
ln -sfn $HOME/.dotfiles/mackup.cfg $HOME/.mackup.cfg

# Install custom Mackup application definitions
mkdir -p $HOME/.mackup
for cfg in $HOME/.dotfiles/mackup/*.cfg; do
    [ -f "$cfg" ] && ln -sfn "$cfg" "$HOME/.mackup/$(basename "$cfg")"
done

# Install oh-my-zsh (unattended so it does not chsh or exec into a new shell)
if [ ! -d $HOME/.oh-my-zsh ]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

# Replace the default oh-my-zsh .zshrc with the dotfiles symlink
rm -f $HOME/.zshrc
ln -s $HOME/.dotfiles/zsh/zshrc $HOME/.zshrc

# Setup global gitignore
git config --global core.excludesfile ~/.gitignore

# Install Depy
chown "$USER" /opt
git clone https://github.com/ivandokov/depy.git /opt/depy
cd /opt/depy
./install
