export PATH=/opt/homebrew/bin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=$HOME/.composer/vendor/bin:$PATH
export PATH=/usr/local/opt/node@10/bin:$PATH
export PATH=/usr/local/opt/node@12/bin:$PATH
export PATH=/usr/local/opt/node@14/bin:$PATH
export PATH=$HOME/.npm-packages/bin:$PATH
export PATH=vendor/bin:$PATH
export PATH=node_modules/.bin:$PATH

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="dokov"

HIST_STAMPS="dd/mm/yyyy"
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
export HISTIGNORE="ls:cd:cd -:pwd:date:* --help"
export HISTORY_IGNORE="(ls|cd|cd -|pwd|date|* --help)"

ZSH_CUSTOM=$HOME/.dotfiles/zsh/custom

plugins=(git laravel composer)

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

export EDITOR=nano

export CLICOLOR=1
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd

export GREP_OPTIONS="--color=auto"

source $HOME/.dotfiles/zsh/aliases.zsh
source $HOME/.dotfiles/zsh/functions.zsh

[ -f /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
