export PATH=.:\
/opt/homebrew/opt/gnu-sed/libexec/gnubin:\
./vendor/bin:\
./node_modules/.bin:\
/opt/homebrew/sbin:\
/opt/homebrew/bin:\
$HOME/.config/phpmon/bin:\
$HOME/.composer/vendor/bin:\
$PATH

export ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM=$HOME/.dotfiles/zsh/custom
ZSH_THEME="dokov"

plugins=(git laravel composer)

source $ZSH/oh-my-zsh.sh

HIST_STAMPS="dd/mm/yyyy"
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
export HISTIGNORE="ls:cd:cd -:pwd:date:* --help"
export HISTORY_IGNORE="(ls|cd|cd -|pwd|date|* --help)"
export LANG=en_US.UTF-8
export EDITOR=nano
export CLICOLOR=1
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd
export GREP_OPTIONS="--color=auto"

fpath+="/opt/homebrew/share/zsh/site-functions"

autoload -Uz compinit
compinit

eval "$(zoxide init zsh)"

# Herd injected PHP 8.4 configuration.
export HERD_PHP_84_INI_SCAN_DIR="/Users/ivan/Library/Application Support/Herd/config/php/84/"

# Herd injected PHP binary.
export PATH="/Users/ivan/Library/Application Support/Herd/bin/":$PATH

# Herd injected PHP 8.5 configuration.
export HERD_PHP_85_INI_SCAN_DIR="/Users/ivan/Library/Application Support/Herd/config/php/85/"

# Herd injected NVM configuration
export NVM_DIR="/Users/ivan/Library/Application Support/Herd/config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

[[ -f "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh" ]] && builtin source "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh"


# Herd injected PHP 7.4 configuration.
export HERD_PHP_74_INI_SCAN_DIR="/Users/ivan/Library/Application Support/Herd/config/php/74/"
